// AUTO-GENERATED by build_manifest.py — do not edit by hand.
window.AVATAR_MANIFEST = {
  "layerOrder": [
    "Wallpaper",
    "HatLong",
    "HairLong",
    "EarringBack",
    "Clothing",
    "Ears",
    "Head",
    "Makeup",
    "HairShort",
    "Earring",
    "Beard",
    "HatShort",
    "Mustache",
    "Mouth",
    "Nose",
    "Eyes",
    "Glasses",
    "Masks",
    "Extras"
  ],
  "palettes": {
    "SkinTone": [
      "FFFFF6",
      "FEF7EB",
      "F8D5C2",
      "EEE3C1",
      "D8BF82",
      "D2946B",
      "AE7242",
      "88563B",
      "715031",
      "593D26"
    ],
    "HairColor": [
      "000000",
      "4E3521",
      "8C3B28",
      "B28E28",
      "F4EA6E",
      "F0E6FF",
      "4D22D2",
      "8E2ABE",
      "3596EC",
      "0ECF7C"
    ],
    "ClothingColor": [
      "CCCCCC",
      "684A23",
      "FFCC3B",
      "4242F4",
      "43B9F9",
      "F48914"
    ],
    "Background": [
      "25E899",
      "9AB730",
      "00A55E",
      "3FCDFF",
      "3E00FF",
      "8E2ABE",
      "D0021B",
      "F9006C",
      "FFCE08",
      "F8E71C",
      "15003E",
      "FFFFFF"
    ]
  },
  "defaults": {
    "SkinTone": "AE7242",
    "HairColor": "000000",
    "ClothingColor": "CCCCCC",
    "Background": "25E899"
  },
  "categories": [
    {
      "key": "Head",
      "label": "Head",
      "optional": false,
      "palette": "SkinTone",
      "options": [
        {
          "id": "0",
          "thumb": "Head/0-AE7242.svg",
          "layers": [
            {
              "layer": "Head",
              "path": "Head/0-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "1",
          "thumb": "Head/1-AE7242.svg",
          "layers": [
            {
              "layer": "Head",
              "path": "Head/1-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "2",
          "thumb": "Head/2-AE7242.svg",
          "layers": [
            {
              "layer": "Head",
              "path": "Head/2-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "3",
          "thumb": "Head/3-AE7242.svg",
          "layers": [
            {
              "layer": "Head",
              "path": "Head/3-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "4",
          "thumb": "Head/4-AE7242.svg",
          "layers": [
            {
              "layer": "Head",
              "path": "Head/4-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        }
      ]
    },
    {
      "key": "Eyes",
      "label": "Eyes",
      "optional": false,
      "palette": null,
      "options": [
        {
          "id": "0",
          "thumb": "Eyes/0.svg",
          "layers": [
            {
              "layer": "Eyes",
              "path": "Eyes/0.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "1",
          "thumb": "Eyes/1.svg",
          "layers": [
            {
              "layer": "Eyes",
              "path": "Eyes/1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "2",
          "thumb": "Eyes/2.svg",
          "layers": [
            {
              "layer": "Eyes",
              "path": "Eyes/2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "3",
          "thumb": "Eyes/3.svg",
          "layers": [
            {
              "layer": "Eyes",
              "path": "Eyes/3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "4",
          "thumb": "Eyes/4.svg",
          "layers": [
            {
              "layer": "Eyes",
              "path": "Eyes/4.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "5",
          "thumb": "Eyes/5.svg",
          "layers": [
            {
              "layer": "Eyes",
              "path": "Eyes/5.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "6",
          "thumb": "Eyes/6.svg",
          "layers": [
            {
              "layer": "Eyes",
              "path": "Eyes/6.svg",
              "palette": null
            }
          ]
        }
      ]
    },
    {
      "key": "Nose",
      "label": "Nose",
      "optional": false,
      "palette": null,
      "options": [
        {
          "id": "0",
          "thumb": "Nose/0.svg",
          "layers": [
            {
              "layer": "Nose",
              "path": "Nose/0.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "1",
          "thumb": "Nose/1.svg",
          "layers": [
            {
              "layer": "Nose",
              "path": "Nose/1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "2",
          "thumb": "Nose/2.svg",
          "layers": [
            {
              "layer": "Nose",
              "path": "Nose/2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "3",
          "thumb": "Nose/3.svg",
          "layers": [
            {
              "layer": "Nose",
              "path": "Nose/3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "4",
          "thumb": "Nose/4.svg",
          "layers": [
            {
              "layer": "Nose",
              "path": "Nose/4.svg",
              "palette": null
            }
          ]
        }
      ]
    },
    {
      "key": "Mouth",
      "label": "Mouth",
      "optional": false,
      "palette": null,
      "options": [
        {
          "id": "0",
          "thumb": "Mouth/0.svg",
          "layers": [
            {
              "layer": "Mouth",
              "path": "Mouth/0.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "1",
          "thumb": "Mouth/1.svg",
          "layers": [
            {
              "layer": "Mouth",
              "path": "Mouth/1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "2",
          "thumb": "Mouth/2.svg",
          "layers": [
            {
              "layer": "Mouth",
              "path": "Mouth/2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "3",
          "thumb": "Mouth/3.svg",
          "layers": [
            {
              "layer": "Mouth",
              "path": "Mouth/3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "4",
          "thumb": "Mouth/4.svg",
          "layers": [
            {
              "layer": "Mouth",
              "path": "Mouth/4.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "5",
          "thumb": "Mouth/5.svg",
          "layers": [
            {
              "layer": "Mouth",
              "path": "Mouth/5.svg",
              "palette": null
            }
          ]
        }
      ]
    },
    {
      "key": "Ears",
      "label": "Ears",
      "optional": false,
      "palette": "SkinTone",
      "options": [
        {
          "id": "0",
          "thumb": "Ears/0-AE7242.svg",
          "layers": [
            {
              "layer": "Ears",
              "path": "Ears/0-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "1",
          "thumb": "Ears/1-AE7242.svg",
          "layers": [
            {
              "layer": "Ears",
              "path": "Ears/1-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "2",
          "thumb": "Ears/2-AE7242.svg",
          "layers": [
            {
              "layer": "Ears",
              "path": "Ears/2-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "3",
          "thumb": "Ears/3-AE7242.svg",
          "layers": [
            {
              "layer": "Ears",
              "path": "Ears/3-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        },
        {
          "id": "Spock",
          "thumb": "Ears/Spock-AE7242.svg",
          "layers": [
            {
              "layer": "Ears",
              "path": "Ears/Spock-{c}.svg",
              "palette": "SkinTone"
            }
          ]
        }
      ]
    },
    {
      "key": "Clothing",
      "label": "Clothing",
      "optional": false,
      "palette": "ClothingColor",
      "options": [
        {
          "id": "cardigan",
          "thumb": "Clothing/cardigan-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/cardigan-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "hoodie",
          "thumb": "Clothing/hoodie-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/hoodie-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "knitsweater",
          "thumb": "Clothing/knitsweater-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/knitsweater-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "plaid",
          "thumb": "Clothing/plaid-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/plaid-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "shirt",
          "thumb": "Clothing/shirt-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/shirt-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "shirtsweater",
          "thumb": "Clothing/shirtsweater-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/shirtsweater-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "spacecadet",
          "thumb": "Clothing/spacecadet-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/spacecadet-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "suit",
          "thumb": "Clothing/suit-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/suit-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "ethlogo",
          "thumb": "Clothing/ethlogo-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/ethlogo-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "cloak",
          "thumb": "Clothing/cloak-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/cloak-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "robe",
          "thumb": "Clothing/robe-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/robe-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "pjs",
          "thumb": "Clothing/pjs-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/pjs-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "elf_inspired",
          "thumb": "Clothing/elf_inspired-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/elf_inspired-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "business_suit",
          "thumb": "Clothing/business_suit-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/business_suit-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "suspender",
          "thumb": "Clothing/suspender-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/suspender-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "gitcoinpro",
          "thumb": "Clothing/gitcoinpro-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/gitcoinpro-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "star_uniform",
          "thumb": "Clothing/star_uniform-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/star_uniform-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "jersey",
          "thumb": "Clothing/jersey-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/jersey-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "charlie",
          "thumb": "Clothing/charlie-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/charlie-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "doctor",
          "thumb": "Clothing/doctor-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/doctor-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "chinese",
          "thumb": "Clothing/chinese-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/chinese-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "blouse",
          "thumb": "Clothing/blouse-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/blouse-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "polkadotblouse",
          "thumb": "Clothing/polkadotblouse-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/polkadotblouse-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "coat",
          "thumb": "Clothing/coat-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/coat-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "crochettop",
          "thumb": "Clothing/crochettop-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/crochettop-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "space_suit",
          "thumb": "Clothing/space_suit-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/space_suit-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "armour",
          "thumb": "Clothing/armour-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/armour-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "pilot",
          "thumb": "Clothing/pilot-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/pilot-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "baseball",
          "thumb": "Clothing/baseball-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/baseball-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "football",
          "thumb": "Clothing/football-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/football-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "lifevest",
          "thumb": "Clothing/lifevest-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/lifevest-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "firefighter",
          "thumb": "Clothing/firefighter-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/firefighter-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "leatherjacket",
          "thumb": "Clothing/leatherjacket-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/leatherjacket-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "martialarts",
          "thumb": "Clothing/martialarts-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/martialarts-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "raincoat",
          "thumb": "Clothing/raincoat-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/raincoat-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "recycle",
          "thumb": "Clothing/recycle-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/recycle-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "chef",
          "thumb": "Clothing/chef-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/chef-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "sailor",
          "thumb": "Clothing/sailor-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/sailor-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        },
        {
          "id": "turtleneck",
          "thumb": "Clothing/turtleneck-CCCCCC.svg",
          "layers": [
            {
              "layer": "Clothing",
              "path": "Clothing/turtleneck-{c}.svg",
              "palette": "ClothingColor"
            }
          ]
        }
      ]
    },
    {
      "key": "HairStyle",
      "label": "Hair",
      "optional": true,
      "palette": "HairColor",
      "options": [
        {
          "id": "None+0",
          "thumb": "HairStyle/0-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/0-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+1",
          "thumb": "HairStyle/1-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/1-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+2",
          "thumb": "HairStyle/2-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/2-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+3",
          "thumb": "HairStyle/3-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/3-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+4",
          "thumb": "HairStyle/4-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/4-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "5+None",
          "thumb": "HairStyle/5-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/5-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "6-back+6-front",
          "thumb": "HairStyle/6-front-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/6-back-{c}.svg",
              "palette": "HairColor"
            },
            {
              "layer": "HairShort",
              "path": "HairStyle/6-front-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "7-back+7-front",
          "thumb": "HairStyle/7-front-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/7-back-{c}.svg",
              "palette": "HairColor"
            },
            {
              "layer": "HairShort",
              "path": "HairStyle/7-front-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "8-back+8-front",
          "thumb": "HairStyle/8-front-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/8-back-{c}.svg",
              "palette": "HairColor"
            },
            {
              "layer": "HairShort",
              "path": "HairStyle/8-front-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "9-back+9-front",
          "thumb": "HairStyle/9-front-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/9-back-{c}.svg",
              "palette": "HairColor"
            },
            {
              "layer": "HairShort",
              "path": "HairStyle/9-front-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+10",
          "thumb": "HairStyle/10-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/10-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "damos_hair-back+damos_hair-front",
          "thumb": "HairStyle/damos_hair-front-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/damos_hair-back-{c}.svg",
              "palette": "HairColor"
            },
            {
              "layer": "HairShort",
              "path": "HairStyle/damos_hair-front-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "long_swoosh-back+long_swoosh-front",
          "thumb": "HairStyle/long_swoosh-front-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/long_swoosh-back-{c}.svg",
              "palette": "HairColor"
            },
            {
              "layer": "HairShort",
              "path": "HairStyle/long_swoosh-front-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+mohawk",
          "thumb": "HairStyle/mohawk-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/mohawk-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+mohawk_inverted",
          "thumb": "HairStyle/mohawk_inverted-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/mohawk_inverted-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+spikey",
          "thumb": "HairStyle/spikey-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/spikey-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+mickey_hair",
          "thumb": "HairStyle/mickey_hair-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/mickey_hair-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+modernhair_1",
          "thumb": "HairStyle/modernhair_1-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/modernhair_1-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+modernhair_2",
          "thumb": "HairStyle/modernhair_2-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/modernhair_2-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "modernhair_3-back+modernhair_3-front",
          "thumb": "HairStyle/modernhair_3-front-000000.svg",
          "layers": [
            {
              "layer": "HairLong",
              "path": "HairStyle/modernhair_3-back-{c}.svg",
              "palette": "HairColor"
            },
            {
              "layer": "HairShort",
              "path": "HairStyle/modernhair_3-front-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+womenhair",
          "thumb": "HairStyle/womenhair-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/womenhair-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+womanhair",
          "thumb": "HairStyle/womanhair-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/womanhair-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+womanhair1",
          "thumb": "HairStyle/womanhair1-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/womanhair1-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+womanhair2",
          "thumb": "HairStyle/womanhair2-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/womanhair2-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+womanhair3",
          "thumb": "HairStyle/womanhair3-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/womanhair3-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+womanhair4",
          "thumb": "HairStyle/womanhair4-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/womanhair4-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+womanhair5",
          "thumb": "HairStyle/womanhair5-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/womanhair5-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+man-hair",
          "thumb": "HairStyle/man-hair-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/man-hair-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+girl_hairstyle1",
          "thumb": "HairStyle/girl_hairstyle1-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/girl_hairstyle1-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+girl_hairstyle2",
          "thumb": "HairStyle/girl_hairstyle2-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/girl_hairstyle2-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+girl_hairstyle3",
          "thumb": "HairStyle/girl_hairstyle3-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/girl_hairstyle3-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+men_hairstyle1",
          "thumb": "HairStyle/men_hairstyle1-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/men_hairstyle1-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "None+men_hairstyle2",
          "thumb": "HairStyle/men_hairstyle2-000000.svg",
          "layers": [
            {
              "layer": "HairShort",
              "path": "HairStyle/men_hairstyle2-{c}.svg",
              "palette": "HairColor"
            }
          ]
        }
      ]
    },
    {
      "key": "FacialHair",
      "label": "Facial Hair",
      "optional": true,
      "palette": "HairColor",
      "options": [
        {
          "id": "Mustache-0",
          "thumb": "FacialHair/Mustache-0-000000.svg",
          "layers": [
            {
              "layer": "Mustache",
              "path": "FacialHair/Mustache-0-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "Mustache-1",
          "thumb": "FacialHair/Mustache-1-000000.svg",
          "layers": [
            {
              "layer": "Mustache",
              "path": "FacialHair/Mustache-1-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "Mustache-2",
          "thumb": "FacialHair/Mustache-2-000000.svg",
          "layers": [
            {
              "layer": "Mustache",
              "path": "FacialHair/Mustache-2-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "Mustache-3",
          "thumb": "FacialHair/Mustache-3-000000.svg",
          "layers": [
            {
              "layer": "Mustache",
              "path": "FacialHair/Mustache-3-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "Beard-0",
          "thumb": "FacialHair/Beard-0-000000.svg",
          "layers": [
            {
              "layer": "Beard",
              "path": "FacialHair/Beard-0-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "Beard-1",
          "thumb": "FacialHair/Beard-1-000000.svg",
          "layers": [
            {
              "layer": "Beard",
              "path": "FacialHair/Beard-1-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "Beard-2",
          "thumb": "FacialHair/Beard-2-000000.svg",
          "layers": [
            {
              "layer": "Beard",
              "path": "FacialHair/Beard-2-{c}.svg",
              "palette": "HairColor"
            }
          ]
        },
        {
          "id": "Beard-3",
          "thumb": "FacialHair/Beard-3-000000.svg",
          "layers": [
            {
              "layer": "Beard",
              "path": "FacialHair/Beard-3-{c}.svg",
              "palette": "HairColor"
            }
          ]
        }
      ]
    },
    {
      "key": "Makeup",
      "label": "Makeup",
      "optional": true,
      "palette": null,
      "options": [
        {
          "id": "ziggy-stardust",
          "thumb": "Makeup/ziggy-stardust.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/ziggy-stardust.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "bolt",
          "thumb": "Makeup/bolt.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/bolt.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "star2",
          "thumb": "Makeup/star2.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/star2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "kiss",
          "thumb": "Makeup/kiss.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/kiss.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "blush",
          "thumb": "Makeup/blush.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/blush.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "eyeliner-green",
          "thumb": "Makeup/eyeliner-green.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/eyeliner-green.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "eyeliner-teal",
          "thumb": "Makeup/eyeliner-teal.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/eyeliner-teal.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "eyeliner-pink",
          "thumb": "Makeup/eyeliner-pink.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/eyeliner-pink.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "eyeliner-red",
          "thumb": "Makeup/eyeliner-red.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/eyeliner-red.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "eyeliner-blue",
          "thumb": "Makeup/eyeliner-blue.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/eyeliner-blue.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "star",
          "thumb": "Makeup/star.svg",
          "layers": [
            {
              "layer": "Makeup",
              "path": "Makeup/star.svg",
              "palette": null
            }
          ]
        }
      ]
    },
    {
      "key": "Accessories",
      "label": "Accessories",
      "optional": true,
      "palette": null,
      "multi": true,
      "options": [
        {
          "id": "Glasses-0",
          "thumb": "Accessories/Glasses-0.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-0.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-1",
          "thumb": "Accessories/Glasses-1.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-2",
          "thumb": "Accessories/Glasses-2.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-3",
          "thumb": "Accessories/Glasses-3.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-4",
          "thumb": "Accessories/Glasses-4.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-4.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-redbow",
          "thumb": "Accessories/HatShort-redbow.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-redbow.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-yellowbow",
          "thumb": "Accessories/HatShort-yellowbow.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-yellowbow.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-ballcap",
          "thumb": "Accessories/HatShort-ballcap.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-ballcap.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-cowboy",
          "thumb": "Accessories/HatShort-cowboy.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-cowboy.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-superwoman-tiara",
          "thumb": "Accessories/HatShort-superwoman-tiara.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-superwoman-tiara.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-headdress",
          "thumb": "Accessories/HatShort-headdress.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-headdress.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-headphones",
          "thumb": "Accessories/HatShort-headphones.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-headphones.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-shortbeanie",
          "thumb": "Accessories/HatShort-shortbeanie.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-shortbeanie.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-tallbeanie",
          "thumb": "Accessories/HatShort-tallbeanie.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-tallbeanie.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-bunnyears",
          "thumb": "Accessories/HatShort-bunnyears.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-bunnyears.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-menorah",
          "thumb": "Accessories/HatShort-menorah.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-menorah.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-pilgrim",
          "thumb": "Accessories/HatShort-pilgrim.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-pilgrim.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-santahat",
          "thumb": "Accessories/HatShort-santahat.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-santahat.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-elfhat",
          "thumb": "Accessories/HatShort-elfhat.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-elfhat.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Earring-0",
          "thumb": "Accessories/Earring-0.svg",
          "layers": [
            {
              "layer": "Earring",
              "path": "Accessories/Earring-0.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Earring-1",
          "thumb": "Accessories/Earring-1.svg",
          "layers": [
            {
              "layer": "Earring",
              "path": "Accessories/Earring-1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "EarringBack-2+Earring-2",
          "thumb": "Accessories/Earring-2.svg",
          "layers": [
            {
              "layer": "EarringBack",
              "path": "Accessories/EarringBack-2.svg",
              "palette": null
            },
            {
              "layer": "Earring",
              "path": "Accessories/Earring-2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Earring-3",
          "thumb": "Accessories/Earring-3.svg",
          "layers": [
            {
              "layer": "Earring",
              "path": "Accessories/Earring-3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Earring-4",
          "thumb": "Accessories/Earring-4.svg",
          "layers": [
            {
              "layer": "Earring",
              "path": "Accessories/Earring-4.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Earring-5",
          "thumb": "Accessories/Earring-5.svg",
          "layers": [
            {
              "layer": "Earring",
              "path": "Accessories/Earring-5.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-jack-o-lantern",
          "thumb": "Accessories/Masks-jack-o-lantern.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-jack-o-lantern.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-guy-fawkes",
          "thumb": "Accessories/Masks-guy-fawkes.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-guy-fawkes.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-bunny",
          "thumb": "Accessories/Masks-bunny.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-bunny.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-blackpanther",
          "thumb": "Accessories/Masks-blackpanther.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-blackpanther.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-jack-o-lantern-lighted",
          "thumb": "Accessories/Masks-jack-o-lantern-lighted.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-jack-o-lantern-lighted.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-wolverine_inspired",
          "thumb": "Accessories/Masks-wolverine_inspired.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-wolverine_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-captain_inspired",
          "thumb": "Accessories/Masks-captain_inspired.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-captain_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-alien",
          "thumb": "Accessories/Masks-alien.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-alien.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-Parrot",
          "thumb": "Accessories/Extras-Parrot.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-Parrot.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-wonderwoman_inspired",
          "thumb": "Accessories/Extras-wonderwoman_inspired.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-wonderwoman_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-santa_inspired",
          "thumb": "Accessories/Extras-santa_inspired.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-santa_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-reindeer",
          "thumb": "Accessories/Extras-reindeer.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-reindeer.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-gitcoinbot",
          "thumb": "Accessories/Masks-gitcoinbot.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-gitcoinbot.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-tattoo",
          "thumb": "Accessories/Extras-tattoo.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-tattoo.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-batman_inspired",
          "thumb": "Accessories/Masks-batman_inspired.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-batman_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-flash_inspired",
          "thumb": "Accessories/Masks-flash_inspired.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-flash_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-deadpool_inspired",
          "thumb": "Accessories/Masks-deadpool_inspired.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-deadpool_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-darth_inspired",
          "thumb": "Accessories/Masks-darth_inspired.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-darth_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-spiderman_inspired",
          "thumb": "Accessories/Masks-spiderman_inspired.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-spiderman_inspired.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-5",
          "thumb": "Accessories/Glasses-5.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-5.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-geordi-visor",
          "thumb": "Accessories/Glasses-geordi-visor.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-geordi-visor.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-funny_face",
          "thumb": "Accessories/Masks-funny_face.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-funny_face.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-viking",
          "thumb": "Accessories/Masks-viking.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-viking.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-construction_helmet",
          "thumb": "Accessories/Masks-construction_helmet.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-construction_helmet.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-6",
          "thumb": "Accessories/Glasses-6.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-6.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-green",
          "thumb": "Accessories/HatShort-green.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-green.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Earring-6",
          "thumb": "Accessories/Earring-6.svg",
          "layers": [
            {
              "layer": "Earring",
              "path": "Accessories/Earring-6.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-necklace",
          "thumb": "Accessories/Extras-necklace.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-necklace.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-carnival",
          "thumb": "Accessories/Masks-carnival.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-carnival.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-gas",
          "thumb": "Accessories/Masks-gas.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-gas.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-surgical",
          "thumb": "Accessories/Masks-surgical.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-surgical.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-monkey",
          "thumb": "Accessories/Extras-monkey.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-monkey.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-power",
          "thumb": "Accessories/Masks-power.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-power.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-7",
          "thumb": "Accessories/Glasses-7.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-7.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-8",
          "thumb": "Accessories/Glasses-8.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-8.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-angel",
          "thumb": "Accessories/HatShort-angel.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-angel.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-devil",
          "thumb": "Accessories/HatShort-devil.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-devil.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-necklace1",
          "thumb": "Accessories/Extras-necklace1.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-necklace1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-necklace2",
          "thumb": "Accessories/Extras-necklace2.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-necklace2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-necklace3",
          "thumb": "Accessories/Extras-necklace3.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-necklace3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-9",
          "thumb": "Accessories/Glasses-9.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-9.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-clown",
          "thumb": "Accessories/Masks-clown.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-clown.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-sleepy",
          "thumb": "Accessories/HatShort-sleepy.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-sleepy.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Earring-tribal",
          "thumb": "Accessories/Earring-tribal.svg",
          "layers": [
            {
              "layer": "Earring",
              "path": "Accessories/Earring-tribal.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-google",
          "thumb": "Accessories/Glasses-google.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-google.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-marshmellow",
          "thumb": "Accessories/Masks-marshmellow.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-marshmellow.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-power1",
          "thumb": "Accessories/Masks-power1.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-power1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-elf",
          "thumb": "Accessories/HatShort-elf.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-elf.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-necklaceb",
          "thumb": "Accessories/Extras-necklaceb.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-necklaceb.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-football",
          "thumb": "Accessories/Masks-football.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-football.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-chefHat",
          "thumb": "Accessories/HatShort-chefHat.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-chefHat.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-captain",
          "thumb": "Accessories/HatShort-captain.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-captain.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-beanie",
          "thumb": "Accessories/HatShort-beanie.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-beanie.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-egypt",
          "thumb": "Accessories/Masks-egypt.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-egypt.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-nefertiti",
          "thumb": "Accessories/HatShort-nefertiti.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-nefertiti.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-frankenstein",
          "thumb": "Accessories/Masks-frankenstein.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-frankenstein.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-diving",
          "thumb": "Accessories/Masks-diving.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-diving.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-1",
          "thumb": "Accessories/HatShort-1.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-1.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-artist",
          "thumb": "Accessories/HatShort-artist.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-artist.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-pirate",
          "thumb": "Accessories/HatShort-pirate.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-pirate.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-grad",
          "thumb": "Accessories/HatShort-grad.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-grad.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-antlers",
          "thumb": "Accessories/HatShort-antlers.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-antlers.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-sword",
          "thumb": "Accessories/Extras-sword.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-sword.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-pirate",
          "thumb": "Accessories/Masks-pirate.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-pirate.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-bird",
          "thumb": "Accessories/Extras-bird.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-bird.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Extras-fire",
          "thumb": "Accessories/Extras-fire.svg",
          "layers": [
            {
              "layer": "Extras",
              "path": "Accessories/Extras-fire.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-hockey",
          "thumb": "Accessories/Masks-hockey.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-hockey.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Masks-snorkel",
          "thumb": "Accessories/Masks-snorkel.svg",
          "layers": [
            {
              "layer": "Masks",
              "path": "Accessories/Masks-snorkel.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "Glasses-monocle",
          "thumb": "Accessories/Glasses-monocle.svg",
          "layers": [
            {
              "layer": "Glasses",
              "path": "Accessories/Glasses-monocle.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-police",
          "thumb": "Accessories/HatShort-police.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-police.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-mexican",
          "thumb": "Accessories/HatShort-mexican.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-mexican.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "HatShort-fez",
          "thumb": "Accessories/HatShort-fez.svg",
          "layers": [
            {
              "layer": "HatShort",
              "path": "Accessories/HatShort-fez.svg",
              "palette": null
            }
          ]
        }
      ]
    },
    {
      "key": "Wallpaper",
      "label": "Wallpaper",
      "optional": true,
      "palette": null,
      "options": [
        {
          "id": "portal",
          "thumb": "Wallpaper/portal.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/portal.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "space",
          "thumb": "Wallpaper/space.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/space.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "bokeh",
          "thumb": "Wallpaper/bokeh.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/bokeh.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "bokeh2",
          "thumb": "Wallpaper/bokeh2.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/bokeh2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "bokeh3",
          "thumb": "Wallpaper/bokeh3.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/bokeh3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "bokeh4",
          "thumb": "Wallpaper/bokeh4.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/bokeh4.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "bokeh5",
          "thumb": "Wallpaper/bokeh5.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/bokeh5.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "fire",
          "thumb": "Wallpaper/fire.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/fire.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "trees",
          "thumb": "Wallpaper/trees.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/trees.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "trees2",
          "thumb": "Wallpaper/trees2.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/trees2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "trees3",
          "thumb": "Wallpaper/trees3.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/trees3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "flowers",
          "thumb": "Wallpaper/flowers.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/flowers.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "city",
          "thumb": "Wallpaper/city.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/city.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "city2",
          "thumb": "Wallpaper/city2.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/city2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "mountains",
          "thumb": "Wallpaper/mountains.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/mountains.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "code",
          "thumb": "Wallpaper/code.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/code.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "code2",
          "thumb": "Wallpaper/code2.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/code2.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "code3",
          "thumb": "Wallpaper/code3.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/code3.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "bokeh6",
          "thumb": "Wallpaper/bokeh6.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/bokeh6.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "abstract",
          "thumb": "Wallpaper/abstract.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/abstract.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "anchors",
          "thumb": "Wallpaper/anchors.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/anchors.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "circuit",
          "thumb": "Wallpaper/circuit.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/circuit.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "jigsaw",
          "thumb": "Wallpaper/jigsaw.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/jigsaw.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "lines",
          "thumb": "Wallpaper/lines.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/lines.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "gears",
          "thumb": "Wallpaper/gears.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/gears.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "clouds",
          "thumb": "Wallpaper/clouds.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/clouds.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "signal",
          "thumb": "Wallpaper/signal.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/signal.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "polka_dots",
          "thumb": "Wallpaper/polka_dots.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/polka_dots.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "polka_dots_black",
          "thumb": "Wallpaper/polka_dots_black.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/polka_dots_black.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "squares",
          "thumb": "Wallpaper/squares.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/squares.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "shapes",
          "thumb": "Wallpaper/shapes.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/shapes.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "sunburst",
          "thumb": "Wallpaper/sunburst.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/sunburst.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "sunburst_pastel",
          "thumb": "Wallpaper/sunburst_pastel.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/sunburst_pastel.svg",
              "palette": null
            }
          ]
        },
        {
          "id": "rainbow",
          "thumb": "Wallpaper/rainbow.svg",
          "layers": [
            {
              "layer": "Wallpaper",
              "path": "Wallpaper/rainbow.svg",
              "palette": null
            }
          ]
        }
      ]
    }
  ]
};
